name: Update Officer Data

on:
  issues:
    types: [opened, reopened]

jobs:
  update_officer:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'automation:artwork') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Issue Form
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - run: node scripts/update-artwork.js
        env:
          FORM_DATA: ${{ steps.parse.outputs.payload }}

      - name: Expose artwork Name
        id: artwork-name
        uses: actions/github-script@v5
        with:
          script: return JSON.parse(process.env["FORM_DATA"])["artwork Name"]
          result-encoding: string
        env:
          FORM_DATA: ${{ steps.parse.outputs.payload }}

      - name: Create Pull Request
        id: pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated artwork data
          title: 'Add/Update artwork ${{ steps.artwork-name.outputs.result }}'
          branch: 'automation/${{ github.event.issue.number }}'
          body: |
            This PR was automatically generated by our [`update_artwork.yaml`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/main/.github/workflows/update_artwork.yaml) workflow. For more info, see [`CONTRIBUTING.md`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/main/CONTRIBUTING.md#creating-artwork-update-request).
            Resolves \#${{ github.event.issue.number }} ✨
